name: Gold Price WhatsApp Bot

on:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST daily
  workflow_dispatch:  # allows manual trigger

jobs:
  send-gold-price:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run WhatsApp bot
      env:
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      run: python send_gold_price.py
